/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	PetApiService := openapi.NewPetApiService()
	PetApiController := openapi.NewPetApiController(PetApiService)

	StoreApiService := openapi.NewStoreApiService()
	StoreApiController := openapi.NewStoreApiController(StoreApiService)

	UserApiService := openapi.NewUserApiService()
	UserApiController := openapi.NewUserApiController(UserApiService)

	router := openapi.NewRouter(PetApiController, StoreApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
